name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_linux:
    name: Build on Linux Systems
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            cuda: "11.3"
            optix: "7.3.0"
            ospray: "2.5.0"
            arch: 86
          # - os: ubuntu-18.04
          #   cuda: "10.2"
          #   optix: "7.3.0"
          #   ospray: "2.5.0"
          #   arch: 75

    env:
      build_dir: "build"
      config: "Release"
      GDT_CUDA_ARCHITECTURES: ${{ matrix.arch }}

    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install cmake gcc g++ libtbb-dev libglfw3-dev xorg-dev

      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install OptiX
        shell: bash
        run: bash ./optix-cmake-github-actions/install_optix.sh
        env:
          optix: ${{ matrix.optix }}

      - name: Install OSPRay
        shell: bash
        run: bash ./ospray-cmake-github-actions/install_ospray_ubuntu.sh
        env:
          ospray: ${{ matrix.ospray }}

      - name: Install CUDA
        shell: bash
        run: bash ./cuda-cmake-github-actions/scripts/actions/install_cuda_ubuntu.sh
        env:
          cuda: ${{ matrix.cuda }}

      - name: CMake
        run: cmake . -B ${{ env.build_dir }} -DCMAKE_BUILD_TYPE=${{ env.config }} -DBUILD_OPTIX7=ON -DBUILD_OSPRAY=ON -Dospray_DIR=${{ env.OSPRAY_CMAKE_DIR }}
        env: 
          OptiX_INSTALL_DIR: ${{ env.OptiX_INSTALL_DIR }}

      - name: Build
        working-directory: ${{ env.build_dir }}
        run: cmake --build . --target all --verbose -j `nproc`

  build_windows:
    name: Build on Windows
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-2019
            visual_studio: "Visual Studio 16 2019"
            cuda: "11.5.1"
            optix: "7.3.0"
            ospray: "2.5.0"
            arch: 86
          # - os: windows-2019
          #   visual_studio: "Visual Studio 16 2019"
          #   cuda: "11.5.1"
          #   optix: "7.3.0"
          #   arch: 75

    env:
      build_dir: "build"
      config: "Release"
      GDT_CUDA_ARCHITECTURES: ${{ matrix.arch }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install OptiX
        shell: powershell
        run: .\optix-cmake-github-actions\install_optix.ps1
        env:
          optix: ${{ matrix.optix }}

      - name: Install OSPRay
        shell: powershell
        run: .\ospray-cmake-github-actions\install_ospray_ubuntu.ps1
        env:
          ospray: ${{ matrix.ospray }}

      - name: Install CUDA
        shell: powershell
        env:
          cuda: ${{ matrix.cuda }}
          visual_studio: ${{ matrix.visual_studio }}
        run: .\cuda-cmake-github-actions\scripts\actions\install_cuda_windows.ps1

      - name: CMake
        run: cmake . -B ${{ env.build_dir }} -G "${{ matrix.visual_studio }}" -A x64 -DCMAKE_BUILD_TYPE=${{ env.config }} -DBUILD_OPTIX7=ON -DBUILD_OSPRAY=OFF

      - name: Build
        working-directory: ${{ env.build_dir }}
        run: cmake --build . --config ${{ env.config }} --target ALL_BUILD --verbose
